name: Bart Zwemmer
theme: jekyll-theme-minimal
title: Welcome to Bart Zwemmer's personal page
description: On this page I will share projects, ideas and insight about some of my favorit subjects: GIS, Big Data and photography. 
